# Lint configuration for chart testing
# https://github.com/helm/chart-testing/blob/main/doc/linting.md

# Rules to disable
rules:
    # Disable maintainer validation for testing charts
    maintainer: false
    
    # Disable version increment check for testing
    version: false
    
    # Allow missing values.yaml
    missing-values-file: false
    
    # Allow missing README
    missing-readme: false