apiVersion: v2
name: glauth
description: A Helm chart for GLAuth LDAP server
type: application
version: 25.08.06
appVersion: "2.3.2"
keywords:
  - ldap
  - authentication
  - directory
home: https://github.com/hlebkanonik/glauth-helm-chart
sources:
  - https://github.com/hlebkanonik/glauth-helm-chart