apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "glauth.fullname" . }}-config
  labels:
    {{- include "glauth.labels" . | nindent 4 }}
data:
  config.cfg: |
{{ .Values.appConfig | nindent 4 }} 