apiVersion: v1
kind: Service
metadata:
  name: {{ include "glauth.fullname" . }}
  labels:
    {{- include "glauth.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ldapPort }}
      targetPort: ldap
      protocol: TCP
      name: ldap
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.ldap }}
      nodePort: {{ .Values.service.nodePorts.ldap }}
      {{- end }}
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.api }}
      nodePort: {{ .Values.service.nodePorts.api }}
      {{- end }}
  selector:
    {{- include "glauth.labels" . | nindent 4 }}
