apiVersion: v1
kind: Service
metadata:
  name: {{ include "glauth.fullname" . }}
  labels:
    {{- include "glauth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ldapPort }}
      targetPort: ldap
      protocol: TCP
      name: ldap
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "glauth.selectorLabels" . | nindent 4 }}
