name: Release Chart

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Validate Chart
        run: |
          helm lint glauth/
          helm template glauth/ > /dev/null

      - name: Bump Chart Version
        run: |
          chmod +x scripts/bump-version.sh
          ./scripts/bump-version.sh

      - name: Commit Version Bump
        run: |
          git add glauth/Chart.yaml
          git commit -m "Bump chart version to $(date +%y.%m.%d) [skip ci]" || echo "No changes to commit"

      - name: Push Version Bump
        run: |
          git push origin HEAD:${{ github.ref }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          charts_dir: glauth
          config: cr.yaml 